// ── Type Exports ─────────────────────────────────────────────────────────────

export type {
  UserRole,
  User,
  AuthTokens,
  AuthResponse,
  LoginRequest,
  RegisterRequest,
  PasswordResetRequest,
  VerifyEmailRequest,
} from "./auth";

export type {
  EventType,
  StreamingProvider,
  EventCategory,
  EventCountry,
  CommunityType,
  TicketType as EventTicketType,
  AttendanceType as EventAttendanceType,
  Ticket,
  TicketAvailability,
  StreamingConfig,
  Event,
  EventDraft,
  EventFilterParams,
  EventFilterResult,
  CityStats,
  CommunityInfo,
} from "./events";

export type {
  TicketType,
  AttendanceType,
  OrderStatus,
  OrderItem,
  Order,
  PaymentMethod,
  PaymentRequest,
  PaymentResponse,
  RefundRequest,
  RefundStatus,
  Refund,
  VirtualAccess,
  CryptoBalance,
  Wallet,
  TransactionType,
  Transaction,
  PromoCreditType,
  PromoCredit,
} from "./orders";

export type {
  ProductCategory,
  FulfillmentType,
  Product,
  ProductBundle,
  CartItem,
  MerchOrderItem,
  ShippingAddress,
  MerchOrder,
} from "./merchandise";

export type {
  VendorCategory,
  VendorCity,
  VendorStatus,
  VendorSubscriptionPlan,
  VendorSubscription,
  VendorProfile,
  PricingModel,
  ServiceProfile,
  VendorReview,
  VendorInvitationStatus,
  VendorInvitation,
  VendorAnalytics,
} from "./vendors";

export type {
  CryptoSymbol,
  CryptoBalance as WalletCryptoBalance,
  Wallet as WalletBalance,
  TransactionType as WalletTransactionType,
  Transaction as WalletTransaction,
  SavingsTarget,
  ReminderType,
  Reminder,
  GroupType,
  GroupPermissions,
  GroupWalletMember,
  GroupWalletStatus,
  GroupWallet,
  GroupContribution,
  GroupNotificationType,
  GroupNotification,
  CryptoDepositStatus,
  CryptoDeposit,
  WithdrawalStatus,
  WithdrawalRequest,
} from "./wallet";

export type {
  InsightType,
  EventInsight,
  EventMetrics,
  BenchmarkData,
  OrganizerEventHistory,
  GrowthTrend,
  OrganizerPerformancePattern,
  VirtualAnalytics as EventVirtualAnalytics,
  NotificationType,
  Notification,
  NotificationPreferences,
  UserLocation,
  GeoNotification,
  UserProfile,
  FollowType,
  Follow,
} from "./analytics";

export type {
  AnnouncementTargetType,
  AnnouncementPriority,
  AnnouncementStatus,
  Announcement,
  AnnouncementView,
  DisputeStatus,
  DisputeReason,
  Dispute,
  RefundStatus as RefundProcessingStatus,
  RefundProcessing,
  CommissionStatus,
  EventCommission,
  CommissionSettlementStatus,
  CommissionSettlement,
  CommissionReport,
  FraudStatus,
  FraudType,
  FraudCase,
  AuditAction,
  AuditLog,
  ChatMessageType,
  ChatMessage,
  UserPresenceStatus,
  UserPresence,
  Poll,
  PollVote,
  QAQuestion,
  ReactionType,
  Reaction,
  VirtualAttendee,
  WatchSession,
  DiscussionThread,
  DiscussionReply,
} from "./admin";

export type {
  ApiSuccessResponse,
  ApiErrorResponse,
  ApiResponse,
  PaginatedResponse,
  SearchType,
  SearchRequest,
  SearchResult,
  SearchResponse,
  CityStatsResponse,
  CityEventsResponse,
  HeatmapPoint,
  HeatmapResponse,
  IdentityStatus,
  IdentityDocument,
  ContentStatus,
  BlogPost,
  ReferralStats,
  ReferralReward,
  CampaignStatus,
  CampaignType,
  Campaign,
  CampaignMetrics,
} from "./api";
