import { NextRequest, NextResponse } from "next/server";
import { getDocument } from "@/lib/store";
import { getEventById } from "@/lib/events";

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ id: string; docId: string }> }
) {
  const { id, docId } = await params;

  const doc = getDocument(id, docId);
  const event = getEventById(id);

  if (!doc || !event) {
    return NextResponse.json(
      { ok: false, error: "Document or event not found" },
      { status: 404 }
    );
  }

  // Generate HTML content for PDF
  let htmlContent = "";

  if (doc.type === "charter") {
    htmlContent = generateCharterHTML(doc, event);
  } else if (doc.type === "rundown") {
    htmlContent = generateRundownHTML(doc, event);
  } else {
    return NextResponse.json(
      { ok: false, error: "PDF export not supported for this document type" },
      { status: 400 }
    );
  }

  // Return HTML that can be printed to PDF by the browser
  return new NextResponse(htmlContent, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `inline; filename="${doc.title}.html"`,
    },
  });
}

function generateCharterHTML(doc: any, event: any): string {
  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${doc.title}</title>
  <style>
    @page {
      margin: 2cm;
    }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 800px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #1a1a1a;
      border-bottom: 3px solid #4392f1;
      padding-bottom: 10px;
      margin-bottom: 30px;
    }
    h2 {
      color: #2c3e50;
      margin-top: 30px;
      margin-bottom: 15px;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
    }
    .event-info {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .event-info p {
      margin: 5px 0;
    }
    .content-section {
      margin-bottom: 25px;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
    @media print {
      body {
        padding: 0;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${doc.title}</h1>
  </div>
  
  <div class="event-info">
    <p><strong>Event:</strong> ${event.title}</p>
    <p><strong>Date:</strong> ${new Date(event.date).toLocaleDateString()}</p>
    <p><strong>Location:</strong> ${event.city}${event.venue ? `, ${event.venue}` : ""}</p>
    <p><strong>Document Created:</strong> ${new Date(doc.createdAt).toLocaleDateString()}</p>
  </div>
  
  <div class="content-section">
    <pre style="white-space: pre-wrap; font-family: inherit;">${doc.content}</pre>
  </div>
  
  <div class="footer">
    <p>Generated by Guestly Event Management Platform</p>
    <p>${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
  `;
}

function generateRundownHTML(doc: any, event: any): string {
  const items = doc.rundownItems || [];
  
  const itemsHTML = items
    .map(
      (item: any) => `
    <tr>
      <td style="padding: 12px; border-bottom: 1px solid #e0e0e0; font-weight: 600;">${item.time}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e0e0e0;">${item.duration} min</td>
      <td style="padding: 12px; border-bottom: 1px solid #e0e0e0;">
        <strong>${item.activity}</strong>
        ${item.description ? `<br><span style="color: #666; font-size: 14px;">${item.description}</span>` : ""}
      </td>
      <td style="padding: 12px; border-bottom: 1px solid #e0e0e0;">${item.responsible || "-"}</td>
      <td style="padding: 12px; border-bottom: 1px solid #e0e0e0;">${item.location || "-"}</td>
    </tr>
  `
    )
    .join("");

  return `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${doc.title}</title>
  <style>
    @page {
      margin: 2cm;
    }
    body {
      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
      line-height: 1.6;
      color: #333;
      max-width: 1000px;
      margin: 0 auto;
      padding: 20px;
    }
    h1 {
      color: #1a1a1a;
      border-bottom: 3px solid #4392f1;
      padding-bottom: 10px;
      margin-bottom: 30px;
    }
    .header {
      text-align: center;
      margin-bottom: 40px;
    }
    .event-info {
      background: #f8f9fa;
      padding: 15px;
      border-radius: 8px;
      margin-bottom: 30px;
    }
    .event-info p {
      margin: 5px 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }
    th {
      background: #4392f1;
      color: white;
      padding: 12px;
      text-align: left;
      font-weight: 600;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #ddd;
      text-align: center;
      font-size: 12px;
      color: #666;
    }
    @media print {
      body {
        padding: 0;
      }
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${doc.title}</h1>
  </div>
  
  <div class="event-info">
    <p><strong>Event:</strong> ${event.title}</p>
    <p><strong>Date:</strong> ${new Date(event.date).toLocaleDateString()}</p>
    <p><strong>Location:</strong> ${event.city}${event.venue ? `, ${event.venue}` : ""}</p>
    <p><strong>Total Activities:</strong> ${items.length}</p>
    <p><strong>Document Created:</strong> ${new Date(doc.createdAt).toLocaleDateString()}</p>
  </div>
  
  <table>
    <thead>
      <tr>
        <th>Time</th>
        <th>Duration</th>
        <th>Activity</th>
        <th>Responsible</th>
        <th>Location</th>
      </tr>
    </thead>
    <tbody>
      ${itemsHTML}
    </tbody>
  </table>
  
  <div class="footer">
    <p>Generated by Guestly Event Management Platform</p>
    <p>${new Date().toLocaleDateString()}</p>
  </div>
</body>
</html>
  `;
}
